### ISSUE TITLE
Allow setting the 'backup' parameter on the remote_file resource

### ISSUE THREAD

**Issue by apowers** [chef-cookbooks/ark#134]
We are using ark to download and ':put' a large file. The remote_file resource defaults to keeping five backups of the file. This is causing some disk capacity problems.

Please allow setting a 'backup' parameter on the ark resource that will get passed to the remote_file resource. This should be the simplest way to constrain the amount of storage used by ark resources.

**Comment by iennae** [comment]
#136 was merged in so this should be addressed. Thanks for submitting the fix.
