### ISSUE TITLE
ark on windows runs 7z e instead of x

### ISSUE THREAD

**Issue by EmFl** [chef-cookbooks/ark#138]
Hello,
I think there is a bug in the cookbook but it might be me misunderstanding the concept.
I was thinking that action :put would simply extract the zip in a folder, however, it runs 7z.exe e which extracts files without folder.

Tried with action :dump as well but this also runs 7z e instead of x.
What action should I use to get my folders kept in my extracted directory on windows ?
Thanks

**Comment by EmFl** [comment]
Since then I've change my resource block to
```
ark 'webpipackages' do
 url node['BuildServer']['webpi']['packageurl']
 extension 'zip'
 win_install_dir 'c:\webpipackages'
 strip_components 0
end
```

But I get this

 

> Mixlib::ShellOut::ShellCommandFailed
>  ------------------------------------
>  STDERR: 'unpack' is not recognized as an internal or external command,
>  operable program or batch file.
>  # In /local-mode-cache/cache/cookbooks/ark/providers/default.rb
> 
>   50:   execute "unpack #{new_resource.release_file}" do
>   51:     command unpack_command
>   52:     cwd new_resource.path
>   53:     environment new_resource.environment
>   54:     notifies :run, "execute[set owner on #{new_resource.path}]"
>   55:     action :nothing
>   56:   end
>   57:
> 
>  Compiled Resource:
>  ------------------
>  # Declared in local-mode-cache/cache/cookbooks/ark/providers/default.rb:50:in `block in cla
> om_file'
> 
>  execute("unpack local-mode-cache\cache/webpilocalpackages-1.zip") do
>    action [:nothing]
>    retries 0
>    retry_delay 2
>    default_guard_interpreter :execute
>    command "unpack [...]local-mode-cache\\cache/webpilocalpackages-1.zip"
>    backup 5
>    cwd "c:\\webpipackages"
>    returns 0
>    declared_type :execute
>  end
>

**Comment by netflash** [comment]
I get the same error.
