### ISSUE TITLE
Couldn't test ark notifications using ChefSpec

### ISSUE THREAD

**Issue by szymonpk** [chef-cookbooks/ark#139]
According to official ChefSpec [example](https://github.com/sethvargo/chefspec/blob/master/examples/notifications/spec/default_spec.rb), to test if resource notifies other resource there should be `resource_name` method. In case of ark following code should work:

```ruby
describe "foo::bar" do
  let(:chef_run) { ChefSpec::SoloRunner.converge(described_recipe) }

  it "notifies other resource" do
    expect(chef_run.ark("package")).to notify("execute[command]").to(:run)
  end
end
```

But it throws exception:

```
undefined method `ark' for #<ChefSpec::SoloRunner:0x00000008a66640>
``` 

I'm not sure why, could we fix this somehow?

**Comment by monkey1016** [comment]
I think ark just needs a [custom matcher](https://github.com/sethvargo/chefspec#writing-custom-matchers) added.  I was able to get it functioning by following that and adding a custom matcher in my `spec/support/matchers.rb` :

```ruby
ChefSpec.define_matcher :ark
```
