### ISSUE TITLE
:install only unpack at chef run end

### ISSUE THREAD

**Issue by aileo** [chef-cookbooks/ark#148]
Hello,

I am using ark resource to install some binaries then use them later in the recipe. Unfortunately, it seems the unpack action is only notified so it only occurs at the end of the chef run.

Is there a way to force ark to unzip right after the download ? Or should i add test to my recipe, checking binaries existancy and run the recipe twice (one run to install and one run to execute) ?

I suppose this is related to the #100 somehow.

example :

``` rb

# install myapp
ark 'myapp' do 
  url 'http://myapp.app/myapp.zip'
end

# using myapp, will fail as app.js is not unpacked allready.
bash 'using my app'
  code <<-EOH
  myapp
  EOH
end
```

**Comment by cheeseplus** [comment]
This shouldn't be the case but given the age and lack of detail (chef-client, cookbook versions) we're closing this one but do please open a new issue if this issue still exists.
