### ISSUE TITLE
[QUESTION] libarchive vs ark cookbook?

### ISSUE THREAD

**Issue by pantocrator27** [chef-cookbooks/ark#188]
Does the ark cookbook supersede the libarchive cookbook in terms of functionality?  I used to use libarchive but it does not seem supported any more.

**Comment by cheeseplus** [comment]
In terms of features/functionality it does supersede libarchive. The advantage of libarchive is that it uses ffi-libarchive and as such is Pure ruby. The cookbook can be considered unmaintained so probably best to close this https://github.com/reset/libarchive-cookbook/issues/27
