### ISSUE TITLE
[QUESTION] Is build-essential really a needed dependency of this cookbook?

### ISSUE THREAD

**Issue by pantocrator27** [chef-cookbooks/ark#189]
### Cookbook version
2.2.1

### Question
Is build-essential really a needed dependency of this cookbook?

**Comment by tas50** [comment]
build-essential is potentially used for compilation of the apps so yes you'll need gcc and the like for that.

**Comment by pantocrator27** [comment]
but it does not appear to be used in the code .... i could only find references to it in the documentation, metadata.rb and test-kitchen configuration.  it seems like all of the packages that are needed are installed via attributes.
