### ISSUE TITLE
 Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /etc/profile.d does not exist.

### ISSUE THREAD

**Issue by arunprasathe** [chef-cookbooks/ark#191]
I am trying to run this on a mac. chef detects the machine to be mac. but still this error pops. I even tried to change the directory as /etc/profile which is specific to mac. but still I get the same issue.

Detailed log : 
Synchronizing Cookbooks:
  - ark (3.0.0)
  - dmg (3.1.1)
  - maven (5.0.0)
  - sublime-text (0.1.5)
  - build-essential (8.0.1)
  - windows (3.0.5)
  - seven_zip (2.0.2)
  - java (1.49.0)
  - apt (6.1.0)
  - mingw (2.0.0)
  - ohai (5.0.3)
  - homebrew (4.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 8 resources
Recipe: maven::default
  * ark[maven] action install
    * directory[/usr/local/maven-3.5.0] action create (up to date)
    * remote_file[/Users/arun/PurpleSlate/.chef/file_cache_path/maven-3.5.0.tar.gz] action create (up to date)
    * execute[unpack /Users/arun/PurpleSlate/.chef/file_cache_path/maven-3.5.0.tar.gz] action nothing (skipped due to action :nothing)
    * execute[set owner on /usr/local/maven-3.5.0] action nothing (skipped due to action :nothing)
    * link[/usr/local/maven] action create (up to date)
    * template[/etc/profile/maven.sh] action create
      * Parent directory /etc/profile does not exist.
      ================================================================================
      Error executing action `create` on resource 'template[/etc/profile/maven.sh]'
      ================================================================================
      
      Chef::Exceptions::EnclosingDirectoryDoesNotExist
      ------------------------------------------------
      Parent directory /etc/profile does not exist.
      
      Resource Declaration:
      ---------------------
      # In /Users/arun/PurpleSlate/.chef/file_cache_path/cookbooks/ark/resources/default.rb
      
      101:     template "/etc/profile/#{new_resource.name}.sh" do
      102:       cookbook 'ark'
      103:       source 'add_to_path.sh.erb'
      104:       owner 'root'
      105:       group node['root_group']
      106:       mode '0755'
      107:       cookbook 'ark'
      108:       variables(directory: "#{new_resource.path}/bin")
      109:       only_if { new_resource.append_env_path }
      110:     end
      111:   end
      
      Compiled Resource:
      ------------------
      # Declared in /Users/arun/PurpleSlate/.chef/file_cache_path/cookbooks/ark/resources/default.rb:101:in `block in class_from_file'
      
      template("/etc/profile/maven.sh") do
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        source "add_to_path.sh.erb"
        cookbook "ark"
        variables {:directory=>"/usr/local/maven-3.5.0/bin"}
        declared_type :template
        cookbook_name "maven"
        mode "0755"
        owner "root"
        group "wheel"
        path "/etc/profile/maven.sh"
        only_if { #code block }
      end
      
      Platform:
      ---------
      x86_64-darwin14
      
    
    ================================================================================
    Error executing action `install` on resource 'ark[maven]'
    ================================================================================
    
    Chef::Exceptions::EnclosingDirectoryDoesNotExist
    ------------------------------------------------
    template[/etc/profile/maven.sh] (/Users/arun/PurpleSlate/.chef/file_cache_path/cookbooks/ark/resources/default.rb line 101) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /etc/profile does not exist.
    
    Resource Declaration:
    ---------------------
    # In /Users/arun/PurpleSlate/.chef/file_cache_path/cookbooks/maven/recipes/default.rb
    
     26: ark 'maven' do
     27:   version node['maven']['version']
     28:   url node['maven']['url']
     29:   checksum node['maven']['checksum']
     30:   home_dir node['maven']['m2_home']
     31:   win_install_dir node['maven']['m2_home']
     32:   append_env_path node['maven']['setup_bin']
     33: end
     34: 
    
    Compiled Resource:
    ------------------
    # Declared in /Users/arun/PurpleSlate/.chef/file_cache_path/cookbooks/maven/recipes/default.rb:26:in `from_file'
    
    ark("maven") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :ark
      cookbook_name "maven"
      recipe_name "default"
      version "3.5.0"
      url "http://apache.mirrors.tds.net/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz"
      checksum "beb91419245395bd69a4a6edad5ca3ec1a8b64e41457672dc687c173a495f034"
      home_dir "/usr/local/maven"
      win_install_dir "/usr/local/maven"
      append_env_path true
      extension "tar.gz"
      prefix_bin "/usr/local/bin"
      prefix_root "/usr/local"
      owner "root"
      path "/usr/local/maven-3.5.0"
      release_file "/Users/arun/PurpleSlate/.chef/file_cache_path/maven-3.5.0.tar.gz"
    end
    
    Platform:
    ---------
    x86_64-darwin14
    

Running handlers:
Running handlers complete
Chef Client failed. 0 resources updated in 14 seconds

**Comment by iennae** [comment]
It looks like you are trying to use the maven cookbook: https://github.com/chef-cookbooks/maven which does not have mac os x as a supported platform. The problem that you are sharing doesn't appear to be ark specific. 

On the mac platform /etc/profile is a file and not a directory. In your error message " template "/etc/profile/#{new_resource.name}.sh" do" this is attempting to set up a file there which will fail because /etc/profile is not a directory. 

When you look at the cookbook, check the metadata.rb for the supports keywords that will let you know what OS's are supported.

**Comment by iennae** [comment]
Please reopen with additional details if this is still a problem.
