### ISSUE TITLE
Remove conditional dependencies

### ISSUE THREAD

**Issue by rabidscorpio** [chef-cookbooks/ark#195]
### Cookbook version
3.1.0

### Platform Details
Ubuntu

### Scenario:
I'd really really appreciate it if I didn't have to install and/or maintain cookbooks that I don't need.

### Steps to Reproduce:
Include the ```ark``` cookbook without having the ```windows``` or ```seven_zip``` cookbook installed.

### Expected Result:
I shouldn't have to install random cookbooks for situations that aren't relevant to my environment. Forcing people to include the ```windows``` and ```seven_zip``` cookbooks creates a dependency hell where major upgrades like migrating to chef 13 requires upgrading a bunch of cookbooks that I don't even use. (Ark only has 2 dependencies that aren't essential but because a number of other cookbooks do the same thing, it creates a problem)

### Actual Result:
I get a version constraint error when I try to use the cookbook without ```windows``` and ```seven_zip``` installed.

**Comment by tas50** [comment]
These are necessary dependencies for anyone running Windows so they can't be removed from the cookbook. Removing them would save those from being loaded on your run list, but it would entirely break converges for those users. In general with a depsolver like Berkshelf setup you shouldn't worry or care what dependencies are being brought in when they don't apply to your platform. Chef itself includes resources that only work on macOS, Windows, and even AIX that ship to every node. They're not loaded and have no impact.
