### ISSUE TITLE
Ark can't download from S3.  Could you add functionality to download via the aws cookbook?

### ISSUE THREAD

**Issue by mmclane** [chef-cookbooks/ark#199]
### Cookbook version
3.1.0

### Chef-client version
version 12.19.36

### Platform Details
Windows 2012 R2 running on AWS EC2.

### Scenario:
I would like to use ARK to download a zip from S3 and extract it.  Like this:
ark 'foo' do
  url 'http://install-stuff-us-east-1.s3.amazonaws.com/installers/foo.zip'
  path 'C:/'
  action :put
end

### Steps to Reproduce:
Create a cookbook that pulls a zip file from S3 and then run it via kitchen using the EC2 driver.  Make sure to specify a instance profile that has rights to the file in S3.

### Expected Result:
ark will be able to download the zip and extract it just like any other URL.

### Actual Result:
Currently if I do this, I get a 403 'Forbidden' error unless the bucket is public.  If you were to have a flag or something that indicates its an S3 URL, then you could use the aws cookbook to download the file successfully.

  Net::HTTPServerException
           ------------------------
           remote_file[C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/foo.zip] (C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/ark/resources/default.rb line 139) had an error: Net::HTTPServerException: 403 "Forbidden"

**Comment by iennae** [comment]
Thanks for requesting this feature. This cookbook needs some major refactoring and we aren't going to add additional dependencies to it at this time.

**Comment by moutons** [comment]
It's worth noting that it isn't much work to use https://github.com/chef-cookbooks/aws#aws_s3_file and the `file://` protocol in-recipe to get this done without adding a feature to the cookbook, @mmclane
