### ISSUE TITLE
Fix README.MD please

### ISSUE THREAD

**Issue by kubagruszka** [chef-cookbooks/ark#69]
I faced to misleading descriptions in readme: 

> Actions
> ....
> :install_with_make: extracts the archive to a path, runs make, and make install. It does not run the configure step at this time

In fact I see that this action is doing **configure** as well nowadays

> ark "test_autogen" do
>   url 'https://github.com/zeromq/libzmq/tarball/master'
>   extension "tar.gz"
>   action [ :configure, :install_with_make ]
> end

Based on the example above and definition of install_with_make I configured my recipe to execute ark with :configure and :Install_with_make and that **failed**. It failed because the second action **install_with_make** was terminated after the step of 2nd time downloading the artifact, thus next steps like **make** and **make install** were skipped.

**Comment by acolichia** [comment]
Also, :put is documented to support the "append_env_path" attribute, however this is not the case as of 0.9.0

**Comment by jfloyd** [comment]
just wasted a few hours debugging this issue.  :\  the "action [ :configure, :install_with_make ]" example in the docs frustrated me all night!
