### ISSUE TITLE
Where are the providers for setup_py_build, setup_py_install and setup_py gone?

### ISSUE THREAD

**Issue by sleberrigaud** [chef-cookbooks/ark#73]
It's possible I am missing something as I'm still fairly new to chef. But here it is.

After upgrading from 0.1.0 to 0.9.0 (yes, I know quite the jump) I get errors like the following running chef-client: `Cannot find a resource for action_setup_py_install ...`

After looking at the ark source code for a while, I found that `:setup_py_build, :setup_py_install, :setup_py` are defined/declared in `resources/default.rb` as `allowed_actions` but I can't see their counter part definitions in `providers/default.rb`

I've tried adding my own `setup_py_install` definition in the latter and surely I don't get the error any more...

Am I missing something?

I guess in the mean time I'll copy over the _old_ definition of that action locally for myself.

**Comment by cheeseplus** [comment]
Fixed by #77
