### ISSUE TITLE
Checksum Regex validation Error

### ISSUE THREAD

**Issue by kameshsampath** [chef-cookbooks/ark#89]
The current regex validator for checksum attribute of the ark expects the checksum to be exactly 64 characters `attribute :checksum, regex: /^[a-zA-Z0-9]{64}$/, default: nil` , but ideally thats not the case in the realworld, there are cases where checksum is less than 64 characters as well.

**Comment by burtlo** [comment]
Ark uses the `remote_file` resource when requesting the file. Reading the documentation for [remote file](http://docs.chef.io/resources.html#remote-file)'s checksum:

> Optional, see use_conditional_get. The SHA-256 checksum of the file. Use to prevent the remote_file resource from re-downloading a file. When the local file matches the checksum, the chef-client will not download it.

A SHA-256 generated hash seems to always be 64 characters so I think that requirement of 64-bit is valid.

**Comment by jpmat296** [comment]
I agree on the length of the checksum but I think the regex should be:
/^[a-fA-F0-9]{64}$/

since SHA-256 is hexadecimal, no ?

**Comment by cheeseplus** [comment]
The regex could be tighter but it's not going to break anything and if SHASUM is incorrect it wouldn't validate anyway. Feel free to open a new issue/PR if you'd like to request this as an enhancement but closing as the initial issue has been answered.

**Comment by SahajMahajan** [comment]
Chef ark cookbook doesn't validate checksum of tomcat packages?????
